# Aliases auto generated by nu-alias-converter on 2026-05-01.
# Changes to this file will be overwritten.

alias .. = cd ..
alias ... = cd ../..
alias .... = cd ../../..
alias 1d = cd ..
alias 2d = cd ../..
alias 3d = cd ../../..
# alias sb = source ~/.bashrc # Errors: Can't create alias to parser keyword.
# alias rreload = source ~/.bashrc # Errors: Can't create alias to parser keyword.
alias c = clear
alias cls = clear
alias x = exit
alias hc = history -c
alias ls = eza --icons=always
# alias ll = ls -alF --color=auto # Errors: The `ls` command doesn't have flag `-F`., The `ls` command doesn't have flag `color`.
# alias la = ls -A --color=auto # Errors: The `ls` command doesn't have flag `-A`., The `ls` command doesn't have flag `color`.
# alias lf = ls -l | egrep -v '^d' # Errors: The `ls` command doesn't have flag `-v`.
alias ldir = ls -l | egrep '^d'
alias grep = grep --colour=auto
# alias psg = ps aux | grep -v grep | grep -i # Errors: Extra positional argument., Extra positional argument., Extra positional argument., The `ps` command doesn't have flag `-v`., Extra positional argument., Extra positional argument., Extra positional argument., The `ps` command doesn't have flag `-i`.
# alias path = echo $PATH # Errors: Variable not found.
# alias pathd = echo -e ${PATH//:/\n} # Errors: The `echo` command doesn't have flag `-e`., Parse mismatch during operation.
alias pathz = echo \$PATH | tr ':' '\n' | sort | uniq
alias df = df -h
alias du = du -h
alias mem = free -h
alias cpu = lscpu
# alias topcpu = ps -eo pid,cmd,%mem,%cpu --sort=-%cpu | head # Errors: The `ps` command doesn't have flag `-e`., Extra positional argument., The `ps` command doesn't have flag `sort`., Extra positional argument., Extra positional argument.
alias ports = sudo ss -tulnqp
alias whatsup = service --status-all
# alias au = sudo apt update -y && sudo apt upgrade -y # Errors: The '&&' operator is not supported in Nushell
# alias update = sudo apt update && sudo apt upgrade # Errors: The '&&' operator is not supported in Nushell
# alias sup = sudo apt update && sudo apt upgrade -y # Errors: The '&&' operator is not supported in Nushell
alias yep = sudo apt install
alias nop = sudo apt remove
alias gs = git status
alias gc = git commit -m
alias gb = git branch
alias gr = git remote -v
alias gl = git log --oneline
alias glf = git for-each-ref --sort=-committerdate
alias glp = git log -g --grep='PHP' -10 --pretty='%h - %s - %cn - %cd'
alias g.bah = git reset --hard; git clean -df
alias g.l = git log --oneline --decorate --graph
alias dk = docker
alias dps = sudo docker ps
alias dcp = docker-compose
alias mkb = minikube
alias kga = kubectl get all
alias kb = kubectl --kubeconfig=$HOME/.kube/k8s-1-18-8-do-1-sfo2-1602808957989-kubeconfig.yaml
alias helm = helm --kubeconfig=$HOME/.kube/k8s-1-18-8-do-1-sfo2-1602808957989-kubeconfig.yaml
alias tf = terraform
alias tg = terragrunt
alias tfm = terraform
alias python = python3
alias ptest = python3 -m pytest
# alias dtstamp = date +"%Y%m%d_%H%M%S" # Errors: Extra positional argument.
alias fast = fast --upload --single-line
alias speed = speedtest-cli --simple
# alias ydload = yt-dlp -U && cd "$HOME/Downloads" && yt-dlp --concurrent-fragments 4 -q --no-check # Errors: The '&&' operator is not supported in Nushell
# alias sz = source ~/.zshrc # Errors: Can't create alias to parser keyword.
# alias h = history | tail
# alias bup = brew update && brew upgrade # Errors: The '&&' operator is not supported in Nushell
alias zup = zb outdated | awk '{print $1}' | xargs zb install
alias dotfiles = /opt/homebrew/bin/git --git-dir=$HOME/.dotfiles/.git --work-tree=$HOME/.dotfiles/
alias dot=dotfiles = dot=dotfiles
alias cat = bat --style plain 
alias rm = rm -i
alias trash = trash -i
alias sudo = sudo 
