from:(boss@news.hugoboss.com 
OR newsletter@mktmc.hackett.com 
OR jagent@route.monster.com
OR McDonaldsCanada@canada.mcdonalds.com
OR promo@promo.timhortons.ca
OR email@marketing.basspro.ca
OR sales@firearmsoutletcanada.com
OR email@email.rw-co.com
OR lacoste@club.lacoste.com
OR publications@understandingwar.
OR uber@uber.com
OR donotreply@jobalert.indeed.com
OR noreply@em.pcoptimum.ca
OR offers@promotions.papajohns.com
OR eflyerfeedback@email.canadiantire.ca
OR ubereats@uber.com
OR uber@uber.com
OR go@flyflair.com
OR tommyhilfiger@e.tommy.com
OR deloitte-jobnotification@noreply.jobs2web.com
OR info@account.netflix.com
OR news@newsletter.hellofresh.ca
OR orders@reliablegun.com
OR info@firearmrights.ca
OR notifications@m.wealthsimple.com
OR donotreply@jobalert.indeed.com
OR jobalerts-noreply@linkedin.com
OR noreply@mc.siriusxm.ca
OR @envisiontechsol.com
OR eflyerfeedback@email.canadiantire.ca
OR no-reply@mastercard.dragonpass.com
OR communications@mail.aircanada.com
OR topemployers@naukrigulf.com
OR personalbanking@info.cibc.com
OR sales@firearmsoutletcanada.com
OR noreply@ffca.edsby.com
OR no-reply@marketing.lyftmail.com
OR donotreply@e-news.bmo.com
OR sunlife@info.sunlife.ca
OR tommyhilfiger@e.tommy.com
OR Pixabay@community.pixabay.com
OR recommendedjobs@naukrigulf.com
OR no-reply@rs.ca.nextdoor.com
OR @payments.interac.ca
OR families-noreply@google.com
OR news@newsletter.hellofresh.ca
OR loyalty@loyalty.ms.aa.com
OR @envisiontechsol.com
OR help@townpost.ca
OR @stemia.ca
OR welcome@openrouter.ai
OR notifications@sezzle.com
OR rewards@dough.papajohns.com
OR @naukrigulf.com
OR noreply-service@eufylife.com
) older_than:2m
