[ui]
# Enable the folder sidebar on the left (width in characters)
sidebar-width=20

# Split the remaining space vertically for the message preview
# 'v' creates a left/right split. '40%' allocates 40% width to the email list.
split-direction=v
split-size=40%

# Automatically open the message preview panel when navigating the index
auto-mark-read=false

# Optimize the middle email list column for narrow 3-panel space
#index-columns=date:fit,name:fit,subject:min 20..max 100
#index-columns=flags:3,date>=,name<20%,subject
#column-combined={{if .ThreadPrefix}}{{.Style .ThreadPrefix "thread"}}{{end}}{{.Peer | names | join ", "}}  |  {{.Subject}}  |  {{.DateAutoFormat .Date.Local}}
#index-columns=flags:3,combined:*,date>
#column-combined = {{if .ThreadPrefix}}{{.Style .ThreadPrefix "thread"}}{{end}}{{.Peer | names | join ", "}} - {{.Subject}}
#index-columns=flags:3,name<30%,subject,date>=
column-combined = {{if .ThreadPrefix}}{{.Style .ThreadPrefix "thread"}}{{end}}{{.Peer | names | join ", "}}  |  {{.Subject}}  |  {{.DateAutoFormat .Date.Local}}
#column-date = {{printf "%12s" (.DateAutoFormat .Date.Local)}}
index-columns = flags:3,combined:*,date:8
column-separator=" │ "

# Visual styles
border=line
styleset-dirs=~/.config/aerc/stylesets/
styleset-name=default
#styleset-name=rose-pine
#styleset-name=dracula
#border-char-vertical="│"
#border-char-horizontal="─"
#styleset-name=catppuccin-mocha

message-list-split=v 60

[statusline]
# Status bar configuration at the bottom
statusline-format="[%s] %f"

[viewer]
# Keybindings and pager for the right preview panel
pager=less -R
always-show-mime=false
# This tells aerc to prioritize HTML over plain text
alternatives=text/html,text/plain

[compose]
# Editor settings for composing emails
editor=vim
header-layout=To,Cc,Subject

[filters]
# Render HTML emails cleanly in the preview panel
text/html=w3m -I UTF-8 -T text/html
text/calendar=vdirsyncer
image/* = catimg -w $(tput cols) -
# Alternatively, if you use a script to pass it to w3mimgdisplay:
# image/* = ~/.config/aerc/filters/image-preview.sh

[triggers]
# Terminal notification triggers
mkdir=notify-send "New Mail"

